import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <div>
          <h1>How are you?</h1>
          <span>Go to</span>{' '}
          <Link href="/search" className='underline underline-offset-2 font-medium'>Search Page</Link>
        </div>
      </main>
    </>
  )
}
